[package]
name = "ledger-store"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
fs2 = "0.4.3"
ledger-core = { path = "../ledger-core" }
ledger-rdf = { path = "../ledger-rdf" }
sqlx = { workspace = true, optional = true }
time.workspace = true
tokio = { workspace = true }

[features]
postgres = ["dep:sqlx"]

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
