name: ci-integration
on:
  pull_request:
  workflow_dispatch:
permissions: {contents: read}
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with: {persist-credentials: false}
      - uses: dtolnay/rust-toolchain@b4f984c1e7daae8e175614de3e73a8411a20333c # 1.89.0
      - run: docker compose config --quiet
      - run: ./scripts/test-integration.sh
